### ISSUE TITLE
Twig Functions not applying

### ISSUE THREAD

**Issue by sgehrig** [teqneers/ext-application-bundle#5]
**Moved from moved from https://github.com/teqneers/ext-application/issues/2**

I tried your tutorial with symfony 2.8 and followed every step. My problem now is that the twig functions extjsAppCachePath(),extjsManifestPath(),extjsApplicationId(),extjsBootstrapPath() are not executing. I always get a 500 error. If I remove those twig from the ext.html.twig file the template gets rendered.

My suspicion is that the methods ar not found. Are there any other nessessary steps that If have forgotten?

Anyway a good tutorial thank you for working on this.

**Comment by sgehrig** [comment]
@almare Can you please provide some more information? Debug output, exception messages, your configuration, log excerpts... Without that it's hard to tell what's going wrong.

**Comment by almare** [comment]
For sure. Thx for your fast reply. The first problem is the apache log is not reporting anything. I already checked the permissions and other things. I also had a talk to our sys-admin without success. The errol logging worked before I started to work on your tutorial.

At the moment I only have the twig output which says. 
`Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.`

I konw thats nothing helpfull ..

What I found out is if I remove the twig functions from the template the ext.html.twig gets rendered. My adoption is that this is caused by the twig functions. I f you have any additional hints who to get more informations about the error, I would appreciate your suggestions.

I will attach my config.yml, appKernel.php and the routing.yml may they will help you.
[config.txt](https://github.com/teqneers/ext-application-bundle/files/272291/config.txt)
[AppKernel.txt](https://github.com/teqneers/ext-application-bundle/files/272295/AppKernel.txt)
[routing.txt](https://github.com/teqneers/ext-application-bundle/files/272297/routing.txt)

**Comment by sgehrig** [comment]
Are you running in development or production mode?

**Comment by sgehrig** [comment]
Can you also please check with `console debug:container` whether the `tq_extjs.twig.extension.extjs_extension` service is present and that it has the `twig.extension` tag?

**Comment by almare** [comment]
The tq_extjs.twig.extension.extjs_extension is present and it has the tag in extjs_application.yml
[debugcontainer.txt](https://github.com/teqneers/ext-application-bundle/files/272418/debugcontainer.txt)

**Comment by almare** [comment]
I got it!!  Obviously it was a mistake of misconfiguration. After switching to development AND adding the default routing for AppBundle it worked as discribed. I removed accidently the routing. Anyway thank you for your fast response, your support and help.

**Comment by sgehrig** [comment]
OK - perfect. Don't hesitate to contact me in case of any problems (with the bundle and library).
